"""user registration process

Revision ID: 8c8112305081
Revises: 
Create Date: 2026-03-14 14:56:55.912012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c8112305081'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salt', sa.String(), nullable=False),
    sa.Column('verifier', sa.String(), nullable=True),
    sa.Column('account_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('discord_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_discord_users_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_discord_users')),
    sa.UniqueConstraint('discord_id', name=op.f('uq_discord_users_discord_id')),
    sa.UniqueConstraint('discord_username', name=op.f('uq_discord_users_discord_username'))
    )
    op.create_table('email_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_users_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_email_users')),
    sa.UniqueConstraint('email', name=op.f('uq_email_users_email'))
    )
    op.create_table('telegram_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('telegram_username', sa.String(), nullable=False),
    sa.Column('telegram_full_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_users_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_telegram_users')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_telegram_users_telegram_id')),
    sa.UniqueConstraint('telegram_username', name=op.f('uq_telegram_users_telegram_username'))
    )
    op.create_table('user_login_tokens',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('challenge', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_login_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_login_tokens')),
    sa.UniqueConstraint('token', name=op.f('uq_user_login_tokens_token'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login_tokens')
    op.drop_table('telegram_users')
    op.drop_table('email_users')
    op.drop_table('discord_users')
    op.drop_table('users')
    # ### end Alembic commands ###
